# Generated by Django 3.0.9 on 2020-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('Last_Name', models.CharField(max_length=100, verbose_name='Apellido Completo')),
                ('Pais', models.CharField(max_length=50, verbose_name='Pais de Nacimiento')),
                ('Country', models.CharField(max_length=50, verbose_name='Ciudad de Nacimiento')),
                ('Phone', models.CharField(max_length=15, verbose_name='Número Telefónico')),
                ('Email', models.EmailField(max_length=50, verbose_name='Correo')),
            ],
        ),
    ]
